LOAD DATA local INFILE "C:\ProgramData\MySQL\MySQL Server 8.0\Uploads\zips.csv"
INTO TABLE zips
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;